baseurl: "/"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

collections: 
  writing:
    output: true
  travelling:
    output: true

defaults:
  - scope:
      path: ""
      type: "writing"
    values:
      layout: journal_entry