baseurl: "/"
name: "Qasim Qureshi"
first_name: "Qasim"
occupation: "Software engineer"
city: "Lahore"
education: "University of Portsmouth"
email: "qasim@hey.com"
profile_image: ""

# social links
twitter_username: Qasim_57
github_username:  QasimQureshi
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: Qasimisq
linkedin_username: Qasim-kureshi
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

collections: 
  writing:
    output: true
  travelling:
    output: true

defaults:
  - scope:
      path: ""
      type: "writing"
    values:
      layout: writing