backend:
  name: github
  repo: qasimQureshi/qasim.is

  # name: git-gateway
  # branch: master # Branch to update (master by default)

media_folder: "assets/images/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Journal" # Used in the UI, ie.: "New Post"
    folder: "_writing" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Coverimage", name: "image", widget: "file", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
      - {label: "Publish date", name: "publish_date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL", picker_utc: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Website"
    files:
      - label: "Navigation"
        name: "navigation"
        file: "navigation.yml"
        fields:
          - label: "booga"
            name: "booga"
            widget: "code"
            default_language: "JavaScript"
          
      - label: "Homepage"
        name: "index"
        file: "index.md"
        fields:
          - label: "Subheading"
            name: "subheading"
            widget: "string"
          - label: "Side image"
            name: "image"
            widget: "file"
          - label: "Image blur"
            name: "image_blur"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
  - name: "data"
    label: "My Data"
    files:
      - label: "Personal details"
        name: "qasim"
        file: "identity.yml"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Occupation"
            name: "occupation"
            widget: "string"
          - label: "City"
            name: "city"
            widget: "string"
          - label: "Profile image"
            name: "profile_image"
            widget: "file"
          - label: "Education"
            name: "education"
            widget: "string"
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "Twitter"
            name: "twitter_username"
            widget: "string"
          - label: "GitHub"
            name: "github_username"
            widget: "string"
          - label: "Instagram"
            name: "instagram_username"
            widget: "string"
          - label: "LinkedIn"
            name: "linkedin_username"
            widget: "string"
